export {default as Header} from './Header/Header'
export {default as Nav} from './Nav/Nav'
export {default as Works} from './Works/Works'
export {default as About} from './About/About'
export {default as Contact} from './Contact/Contact'
export {default as Footer} from './Footer/Footer'
export {default as ScrollToTop} from './Scroll/ScrollToTop'